### ISSUE TITLE
giving errors when downloading algorithms specialization

### ISSUE THREAD

**Issue by imperishableavinash** [feng-lei/dl_coursera#4]
dl_coursera --cookies Desktop/cookies.txt --slug algorithms --isSpec --outdir alg --how builtin
Other specialization downloaded successfully but above is giving errors

**Comment by feng-lei** [comment]
When Coursera API is called intensively, errors might show up. So try using only one worker:

```
$ dl_coursera --cookies Desktop/cookies.txt --slug algorithms --isSpec --outdir alg --how builtin --n-worker 1
```

**Comment by imperishableavinash** [comment]
Thanks it worked.

**Comment by imperishableavinash** [comment]
Thanks it worked.
